blank_issues_enabled: false
contact_links:
  - name: ğŸ§ ç”¨æˆ· QQ ç¾¤ / User QQ Group (1045523485)
    url: https://qm.qq.com/q/FBNLBtEPy8
    about: ç•…èŠä½¿ç”¨å¿ƒå¾—ã€æå‡ºå»ºè®®ç­‰ / Chat about usage, share ideas, etc.
